// AUTO-GENERATED by scripts/generate-exports.ts — do not edit by hand.
// Source of truth: src/**/*.meta.json.


import { defineOnce } from "../core/index.js";
import { CeAbbr } from "../components/abbr/abbr.js";

defineOnce("ce-abbr", CeAbbr);

export { CeAbbr };
