// AUTO-GENERATED by scripts/generate-exports.ts — do not edit by hand.
// Source of truth: src/**/*.meta.json.


import { defineOnce } from "../core/index.js";
import { CeAccordion } from "../components/accordion/accordion.js";

defineOnce("ce-accordion", CeAccordion);

export { CeAccordion };
