// AUTO-GENERATED by scripts/generate-exports.ts — do not edit by hand.
// Source of truth: src/**/*.meta.json.


import { defineOnce } from "../core/index.js";
import { CeAttachmentStrip } from "../components/attachment-strip/attachment-strip.js";

defineOnce("ce-attachment-strip", CeAttachmentStrip);

export { CeAttachmentStrip };
