// AUTO-GENERATED by scripts/generate-exports.ts — do not edit by hand.
// Source of truth: src/**/*.meta.json.


import { defineOnce } from "../core/index.js";
import { CeAvatarGroup } from "../components/avatar-group/avatar-group.js";

defineOnce("ce-avatar-group", CeAvatarGroup);

export { CeAvatarGroup };
