// AUTO-GENERATED by scripts/generate-exports.ts — do not edit by hand.
// Source of truth: src/**/*.meta.json.


import { defineOnce } from "../core/index.js";
import { CeAvatar } from "../components/avatar/avatar.js";

defineOnce("ce-avatar", CeAvatar);

export { CeAvatar };
