// AUTO-GENERATED by scripts/generate-exports.ts — do not edit by hand.
// Source of truth: src/**/*.meta.json.


import { defineOnce } from "../core/index.js";
import { CeBadge } from "../components/badge/badge.js";

defineOnce("ce-badge", CeBadge);

export { CeBadge };
