// AUTO-GENERATED by scripts/generate-exports.ts — do not edit by hand.
// Source of truth: src/**/*.meta.json.


import { defineOnce } from "../core/index.js";
import { CeBarRow } from "../components/bar-row/bar-row.js";

defineOnce("ce-bar-row", CeBarRow);

export { CeBarRow };
