// AUTO-GENERATED by scripts/generate-exports.ts — do not edit by hand.
// Source of truth: src/**/*.meta.json.


import { defineOnce } from "../core/index.js";
import { CeBarChart } from "../components/bar-chart/bar-chart.js";

defineOnce("ce-bar-chart", CeBarChart);

export { CeBarChart };
