// AUTO-GENERATED by scripts/generate-exports.ts — do not edit by hand.
// Source of truth: src/**/*.meta.json.


import { defineOnce } from "../core/index.js";
import { CeBookmark } from "../components/bookmark/bookmark.js";

defineOnce("ce-bookmark", CeBookmark);

export { CeBookmark };
