// AUTO-GENERATED by scripts/generate-exports.ts — do not edit by hand.
// Source of truth: src/**/*.meta.json.


import { defineOnce } from "../core/index.js";
import { CeButton } from "../components/button/button.js";

defineOnce("ce-button", CeButton);

export { CeButton };
