// AUTO-GENERATED by scripts/generate-exports.ts — do not edit by hand.
// Source of truth: src/**/*.meta.json.


import { defineOnce } from "../core/index.js";
import { CeCallout } from "../components/callout/callout.js";

defineOnce("ce-callout", CeCallout);

export { CeCallout };
