// AUTO-GENERATED by scripts/generate-exports.ts — do not edit by hand.
// Source of truth: src/**/*.meta.json.


import { defineOnce } from "../core/index.js";
import { CeCenter } from "../components/center/center.js";

defineOnce("ce-center", CeCenter);

export { CeCenter };
