// AUTO-GENERATED by scripts/generate-exports.ts — do not edit by hand.
// Source of truth: src/**/*.meta.json.


import { defineOnce } from "../core/index.js";
import { CeChart } from "../components/chart/chart.js";

defineOnce("ce-chart", CeChart);

export { CeChart };
