// AUTO-GENERATED by scripts/generate-exports.ts — do not edit by hand.
// Source of truth: src/**/*.meta.json.


import { defineOnce } from "../core/index.js";
import { CeChatBubble } from "../components/chat-bubble/chat-bubble.js";

defineOnce("ce-chat-bubble", CeChatBubble);

export { CeChatBubble };
