// AUTO-GENERATED by scripts/generate-exports.ts — do not edit by hand.
// Source of truth: src/**/*.meta.json.


import { defineOnce } from "../core/index.js";
import { CeChatInput } from "../components/chat-input/chat-input.js";

defineOnce("ce-chat-input", CeChatInput);

export { CeChatInput };
