// AUTO-GENERATED by scripts/generate-exports.ts — do not edit by hand.
// Source of truth: src/**/*.meta.json.


import { defineOnce } from "../core/index.js";
import { CeCheckItem } from "../components/check-item/check-item.js";

defineOnce("ce-check-item", CeCheckItem);

export { CeCheckItem };
