// AUTO-GENERATED by scripts/generate-exports.ts — do not edit by hand.
// Source of truth: src/**/*.meta.json.


import { defineOnce } from "../core/index.js";
import { CeChip } from "../components/chip/chip.js";

defineOnce("ce-chip", CeChip);

export { CeChip };
