// AUTO-GENERATED by scripts/generate-exports.ts — do not edit by hand.
// Source of truth: src/**/*.meta.json.


import { defineOnce } from "../core/index.js";
import { CeCitation } from "../components/citation/citation.js";

defineOnce("ce-citation", CeCitation);

export { CeCitation };
