// AUTO-GENERATED by scripts/generate-exports.ts — do not edit by hand.
// Source of truth: src/**/*.meta.json.


import { defineOnce } from "../core/index.js";
import { CeClock } from "../components/clock/clock.js";

defineOnce("ce-clock", CeClock);

export { CeClock };
