// AUTO-GENERATED by scripts/generate-exports.ts — do not edit by hand.
// Source of truth: src/**/*.meta.json.


import { defineOnce } from "../core/index.js";
import { CeCode } from "../components/code/code.js";

defineOnce("ce-code", CeCode);

export { CeCode };
