// AUTO-GENERATED by scripts/generate-exports.ts — do not edit by hand.
// Source of truth: src/**/*.meta.json.


import { defineOnce } from "../core/index.js";
import { CeCombobox } from "../components/combobox/combobox.js";

defineOnce("ce-combobox", CeCombobox);

export { CeCombobox };
