// AUTO-GENERATED by scripts/generate-exports.ts — do not edit by hand.
// Source of truth: src/**/*.meta.json.


import { defineOnce } from "../core/index.js";
import { CeComment } from "../components/comment/comment.js";

defineOnce("ce-comment", CeComment);

export { CeComment };
