// AUTO-GENERATED by scripts/generate-exports.ts — do not edit by hand.
// Source of truth: src/**/*.meta.json.


import { defineOnce } from "../core/index.js";
import { CeCompare } from "../components/compare/compare.js";

defineOnce("ce-compare", CeCompare);

export { CeCompare };
