// AUTO-GENERATED by scripts/generate-exports.ts — do not edit by hand.
// Source of truth: src/**/*.meta.json.


import { defineOnce } from "../core/index.js";
import { CeConfirm } from "../components/confirm/confirm.js";

defineOnce("ce-confirm", CeConfirm);

export { CeConfirm };
