// AUTO-GENERATED by scripts/generate-exports.ts — do not edit by hand.
// Source of truth: src/**/*.meta.json.


import { defineOnce } from "../core/index.js";
import { CeData } from "../components/data/data.js";

defineOnce("ce-data", CeData);

export { CeData };
