// AUTO-GENERATED by scripts/generate-exports.ts — do not edit by hand.
// Source of truth: src/**/*.meta.json.


import { defineOnce } from "../core/index.js";
import { CeDatePicker } from "../components/date-picker/date-picker.js";

defineOnce("ce-date-picker", CeDatePicker);

export { CeDatePicker };
