// AUTO-GENERATED by scripts/generate-exports.ts — do not edit by hand.
// Source of truth: src/**/*.meta.json.


import { defineOnce } from "../core/index.js";
import { CeDecisionTree } from "../components/decision-tree/decision-tree.js";

defineOnce("ce-decision-tree", CeDecisionTree);

export { CeDecisionTree };
