// AUTO-GENERATED by scripts/generate-exports.ts — do not edit by hand.
// Source of truth: src/**/*.meta.json.


import { defineOnce } from "../core/index.js";
import { CeDetails } from "../components/details/details.js";

defineOnce("ce-details", CeDetails);

export { CeDetails };
