// AUTO-GENERATED by scripts/generate-exports.ts — do not edit by hand.
// Source of truth: src/**/*.meta.json.


import { defineOnce } from "../core/index.js";
import { CeDiff } from "../components/diff/diff.js";

defineOnce("ce-diff", CeDiff);

export { CeDiff };
