// AUTO-GENERATED by scripts/generate-exports.ts — do not edit by hand.
// Source of truth: src/**/*.meta.json.


import { defineOnce } from "../core/index.js";
import { CeDonut } from "../components/donut/donut.js";

defineOnce("ce-donut", CeDonut);

export { CeDonut };
