// AUTO-GENERATED by scripts/generate-exports.ts — do not edit by hand.
// Source of truth: src/**/*.meta.json.


import { defineOnce } from "../core/index.js";
import { CeDropdownMenu } from "../components/dropdown-menu/dropdown-menu.js";

defineOnce("ce-dropdown-menu", CeDropdownMenu);

export { CeDropdownMenu };
