// AUTO-GENERATED by scripts/generate-exports.ts — do not edit by hand.
// Source of truth: src/**/*.meta.json.


import { defineOnce } from "../core/index.js";
import { CeDuration } from "../components/duration/duration.js";

defineOnce("ce-duration", CeDuration);

export { CeDuration };
