// AUTO-GENERATED by scripts/generate-exports.ts — do not edit by hand.
// Source of truth: src/**/*.meta.json.


import { defineOnce } from "../core/index.js";
import { CeEmptyState } from "../components/empty-state/empty-state.js";

defineOnce("ce-empty-state", CeEmptyState);

export { CeEmptyState };
