// AUTO-GENERATED by scripts/generate-exports.ts — do not edit by hand.
// Source of truth: src/**/*.meta.json.


import { defineOnce } from "../core/index.js";
import { CeExample } from "../components/example/example.js";

defineOnce("ce-example", CeExample);

export { CeExample };
