// AUTO-GENERATED by scripts/generate-exports.ts — do not edit by hand.
// Source of truth: src/**/*.meta.json.


import { defineOnce } from "../core/index.js";
import { CeFeatureCard } from "../components/feature-card/feature-card.js";

defineOnce("ce-feature-card", CeFeatureCard);

export { CeFeatureCard };
