// AUTO-GENERATED by scripts/generate-exports.ts — do not edit by hand.
// Source of truth: src/**/*.meta.json.


import { defineOnce } from "../core/index.js";
import { CeFeedbackBar } from "../components/feedback-bar/feedback-bar.js";

defineOnce("ce-feedback-bar", CeFeedbackBar);

export { CeFeedbackBar };
