// AUTO-GENERATED by scripts/generate-exports.ts — do not edit by hand.
// Source of truth: src/**/*.meta.json.


import { defineOnce } from "../core/index.js";
import { CeFeedbackSummary } from "../components/feedback-summary/feedback-summary.js";

defineOnce("ce-feedback-summary", CeFeedbackSummary);

export { CeFeedbackSummary };
