// AUTO-GENERATED by scripts/generate-exports.ts — do not edit by hand.
// Source of truth: src/**/*.meta.json.


import { defineOnce } from "../core/index.js";
import { CeFeedbackHeatmap } from "../components/feedback-heatmap/feedback-heatmap.js";

defineOnce("ce-feedback-heatmap", CeFeedbackHeatmap);

export { CeFeedbackHeatmap };
