// AUTO-GENERATED by scripts/generate-exports.ts — do not edit by hand.
// Source of truth: src/**/*.meta.json.


import { defineOnce } from "../core/index.js";
import { CeFeedbackExport } from "../components/feedback-export/feedback-export.js";

defineOnce("ce-feedback-export", CeFeedbackExport);

export { CeFeedbackExport };
