// AUTO-GENERATED by scripts/generate-exports.ts — do not edit by hand.
// Source of truth: src/**/*.meta.json.


import { defineOnce } from "../core/index.js";
import { CeFeedbackSink } from "../components/feedback-sink/feedback-sink.js";

defineOnce("ce-feedback-sink", CeFeedbackSink);

export { CeFeedbackSink };
