// AUTO-GENERATED by scripts/generate-exports.ts — do not edit by hand.
// Source of truth: src/**/*.meta.json.


import { defineOnce } from "../core/index.js";
import { CeField } from "../components/field/field.js";

defineOnce("ce-field", CeField);

export { CeField };
