// AUTO-GENERATED by scripts/generate-exports.ts — do not edit by hand.
// Source of truth: src/**/*.meta.json.


import { defineOnce } from "../core/index.js";
import { CeFileCard } from "../components/file-card/file-card.js";

defineOnce("ce-file-card", CeFileCard);

export { CeFileCard };
