// AUTO-GENERATED by scripts/generate-exports.ts — do not edit by hand.
// Source of truth: src/**/*.meta.json.


import { defineOnce } from "../core/index.js";
import { CeFrame } from "../components/frame/frame.js";

defineOnce("ce-frame", CeFrame);

export { CeFrame };
