// AUTO-GENERATED by scripts/generate-exports.ts — do not edit by hand.
// Source of truth: src/**/*.meta.json.


import { defineOnce } from "../core/index.js";
import { CeHeatCell } from "../components/heat-cell/heat-cell.js";

defineOnce("ce-heat-cell", CeHeatCell);

export { CeHeatCell };
