// AUTO-GENERATED by scripts/generate-exports.ts — do not edit by hand.
// Source of truth: src/**/*.meta.json.


import { defineOnce } from "../core/index.js";
import { CeHero } from "../components/hero/hero.js";

defineOnce("ce-hero", CeHero);

export { CeHero };
