// AUTO-GENERATED by scripts/generate-exports.ts — do not edit by hand.
// Source of truth: src/**/*.meta.json.


import { defineOnce } from "../core/index.js";
import { CeImage } from "../components/image/image.js";

defineOnce("ce-image", CeImage);

export { CeImage };
