// AUTO-GENERATED by scripts/generate-exports.ts — do not edit by hand.
// Source of truth: src/**/*.meta.json.


import { defineOnce } from "../core/index.js";
import { CeInput } from "../components/input/input.js";

defineOnce("ce-input", CeInput);

export { CeInput };
