// AUTO-GENERATED by scripts/generate-exports.ts — do not edit by hand.
// Source of truth: src/**/*.meta.json.


import { defineOnce } from "../core/index.js";
import { CeKeyValue } from "../components/key-value/key-value.js";

defineOnce("ce-key-value", CeKeyValue);

export { CeKeyValue };
