// AUTO-GENERATED by scripts/generate-exports.ts — do not edit by hand.
// Source of truth: src/**/*.meta.json.


import { defineOnce } from "../core/index.js";
import { CeKpi } from "../components/kpi/kpi.js";

defineOnce("ce-kpi", CeKpi);

export { CeKpi };
