// AUTO-GENERATED by scripts/generate-exports.ts — do not edit by hand.
// Source of truth: src/**/*.meta.json.


import { defineOnce } from "../core/index.js";
import { LessonAudio } from "../lesson/lesson-audio/lesson-audio.js";

defineOnce("lesson-audio", LessonAudio);

export { LessonAudio };
