// AUTO-GENERATED by scripts/generate-exports.ts — do not edit by hand.
// Source of truth: src/**/*.meta.json.


import { defineOnce } from "../core/index.js";
import { LessonQuickfire } from "../lesson/lesson-quickfire/lesson-quickfire.js";

defineOnce("lesson-quickfire", LessonQuickfire);

export { LessonQuickfire };
