// AUTO-GENERATED by scripts/generate-exports.ts — do not edit by hand.
// Source of truth: src/**/*.meta.json.


import { defineOnce } from "../core/index.js";
import { LessonMyth } from "../lesson/lesson-myth/lesson-myth.js";

defineOnce("lesson-myth", LessonMyth);

export { LessonMyth };
