// AUTO-GENERATED by scripts/generate-exports.ts — do not edit by hand.
// Source of truth: src/**/*.meta.json.


import { defineOnce } from "../core/index.js";
import { LessonMatch } from "../lesson/lesson-match/lesson-match.js";

defineOnce("lesson-match", LessonMatch);

export { LessonMatch };
