// AUTO-GENERATED by scripts/generate-exports.ts — do not edit by hand.
// Source of truth: src/**/*.meta.json.


import { defineOnce } from "../core/index.js";
import { LessonHint } from "../lesson/lesson-hint/lesson-hint.js";

defineOnce("lesson-hint", LessonHint);

export { LessonHint };
