// AUTO-GENERATED by scripts/generate-exports.ts — do not edit by hand.
// Source of truth: src/**/*.meta.json.


import { defineOnce } from "../core/index.js";
import { LessonReveal } from "../lesson/lesson-reveal/lesson-reveal.js";

defineOnce("lesson-reveal", LessonReveal);

export { LessonReveal };
