// AUTO-GENERATED by scripts/generate-exports.ts — do not edit by hand.
// Source of truth: src/**/*.meta.json.


import { defineOnce } from "../core/index.js";
import { LessonNote } from "../lesson/lesson-note/lesson-note.js";

defineOnce("lesson-note", LessonNote);

export { LessonNote };
