// AUTO-GENERATED by scripts/generate-exports.ts — do not edit by hand.
// Source of truth: src/**/*.meta.json.


import { defineOnce } from "../core/index.js";
import { LessonSummary } from "../lesson/lesson-summary/lesson-summary.js";

defineOnce("lesson-summary", LessonSummary);

export { LessonSummary };
