// AUTO-GENERATED by scripts/generate-exports.ts — do not edit by hand.
// Source of truth: src/**/*.meta.json.


import { defineOnce } from "../core/index.js";
import { LessonConfidence } from "../lesson/lesson-confidence/lesson-confidence.js";

defineOnce("lesson-confidence", LessonConfidence);

export { LessonConfidence };
