// AUTO-GENERATED by scripts/generate-exports.ts — do not edit by hand.
// Source of truth: src/**/*.meta.json.


import { defineOnce } from "../core/index.js";
import { LessonQuiz } from "../lesson/lesson-quiz/lesson-quiz.js";

defineOnce("lesson-quiz", LessonQuiz);

export { LessonQuiz };
