// AUTO-GENERATED by scripts/generate-exports.ts — do not edit by hand.
// Source of truth: src/**/*.meta.json.


import { defineOnce } from "../core/index.js";
import { LessonFrame } from "../lesson/lesson-frame/lesson-frame.js";

defineOnce("lesson-frame", LessonFrame);

export { LessonFrame };
