// AUTO-GENERATED by scripts/generate-exports.ts — do not edit by hand.
// Source of truth: src/**/*.meta.json.


import { defineOnce } from "../core/index.js";
import { LessonGap } from "../lesson/lesson-gap/lesson-gap.js";

defineOnce("lesson-gap", LessonGap);

export { LessonGap };
