// AUTO-GENERATED by scripts/generate-exports.ts — do not edit by hand.
// Source of truth: src/**/*.meta.json.


import { defineOnce } from "../core/index.js";
import { LessonQuestion } from "../lesson/lesson-question/lesson-question.js";

defineOnce("lesson-question", LessonQuestion);

export { LessonQuestion };
