// AUTO-GENERATED by scripts/generate-exports.ts — do not edit by hand.
// Source of truth: src/**/*.meta.json.


import { defineOnce } from "../core/index.js";
import { LessonCompare } from "../lesson/lesson-compare/lesson-compare.js";

defineOnce("lesson-compare", LessonCompare);

export { LessonCompare };
