// AUTO-GENERATED by scripts/generate-exports.ts — do not edit by hand.
// Source of truth: src/**/*.meta.json.


import { defineOnce } from "../core/index.js";
import { LessonStep } from "../lesson/lesson-step/lesson-step.js";

defineOnce("lesson-step", LessonStep);

export { LessonStep };
