// AUTO-GENERATED by scripts/generate-exports.ts — do not edit by hand.
// Source of truth: src/**/*.meta.json.


import { defineOnce } from "../core/index.js";
import { CeLink } from "../components/link/link.js";

defineOnce("ce-link", CeLink);

export { CeLink };
