// AUTO-GENERATED by scripts/generate-exports.ts — do not edit by hand.
// Source of truth: src/**/*.meta.json.


import { defineOnce } from "../core/index.js";
import { CeList } from "../components/list/list.js";

defineOnce("ce-list", CeList);

export { CeList };
