// AUTO-GENERATED by scripts/generate-exports.ts — do not edit by hand.
// Source of truth: src/**/*.meta.json.


import { defineOnce } from "../core/index.js";
import { CeMark } from "../components/mark/mark.js";

defineOnce("ce-mark", CeMark);

export { CeMark };
