// AUTO-GENERATED by scripts/generate-exports.ts — do not edit by hand.
// Source of truth: src/**/*.meta.json.


import { defineOnce } from "../core/index.js";
import { CeMessageGroup } from "../components/message-group/message-group.js";

defineOnce("ce-message-group", CeMessageGroup);

export { CeMessageGroup };
