// AUTO-GENERATED by scripts/generate-exports.ts — do not edit by hand.
// Source of truth: src/**/*.meta.json.


import { defineOnce } from "../core/index.js";
import { CeModal } from "../components/modal/modal.js";

defineOnce("ce-modal", CeModal);

export { CeModal };
