// AUTO-GENERATED by scripts/generate-exports.ts — do not edit by hand.
// Source of truth: src/**/*.meta.json.


import { defineOnce } from "../core/index.js";
import { CePage } from "../components/page/page.js";

defineOnce("ce-page", CePage);

export { CePage };
