// AUTO-GENERATED by scripts/generate-exports.ts — do not edit by hand.
// Source of truth: src/**/*.meta.json.


import { defineOnce } from "../core/index.js";
import { CePagination } from "../components/pagination/pagination.js";

defineOnce("ce-pagination", CePagination);

export { CePagination };
