// AUTO-GENERATED by scripts/generate-exports.ts — do not edit by hand.
// Source of truth: src/**/*.meta.json.


import { defineOnce } from "../core/index.js";
import { CePopover } from "../components/popover/popover.js";

defineOnce("ce-popover", CePopover);

export { CePopover };
