// AUTO-GENERATED by scripts/generate-exports.ts — do not edit by hand.
// Source of truth: src/**/*.meta.json.


import { defineOnce } from "../core/index.js";
import { CePricingTier } from "../components/pricing-tier/pricing-tier.js";

defineOnce("ce-pricing-tier", CePricingTier);

export { CePricingTier };
