// AUTO-GENERATED by scripts/generate-exports.ts — do not edit by hand.
// Source of truth: src/**/*.meta.json.


import { defineOnce } from "../core/index.js";
import { CeProgress } from "../components/progress/progress.js";

defineOnce("ce-progress", CeProgress);

export { CeProgress };
