// AUTO-GENERATED by scripts/generate-exports.ts — do not edit by hand.
// Source of truth: src/**/*.meta.json.


import { defineOnce } from "../core/index.js";
import { CeProsCons } from "../components/pros-cons/pros-cons.js";

defineOnce("ce-pros-cons", CeProsCons);

export { CeProsCons };
