// AUTO-GENERATED by scripts/generate-exports.ts — do not edit by hand.
// Source of truth: src/**/*.meta.json.


import { defineOnce } from "../core/index.js";
import { CeQuote } from "../components/quote/quote.js";

defineOnce("ce-quote", CeQuote);

export { CeQuote };
