// AUTO-GENERATED by scripts/generate-exports.ts — do not edit by hand.
// Source of truth: src/**/*.meta.json.


import { defineOnce } from "../core/index.js";
import { CeRadioGroup } from "../components/radio-group/radio-group.js";

defineOnce("ce-radio-group", CeRadioGroup);

export { CeRadioGroup };
