// AUTO-GENERATED by scripts/generate-exports.ts — do not edit by hand.
// Source of truth: src/**/*.meta.json.


import { defineOnce } from "../core/index.js";
import { CeRankList } from "../components/rank-list/rank-list.js";

defineOnce("ce-rank-list", CeRankList);

export { CeRankList };
