// AUTO-GENERATED by scripts/generate-exports.ts — do not edit by hand.
// Source of truth: src/**/*.meta.json.


import { defineOnce } from "../core/index.js";
import { CeRating } from "../components/rating/rating.js";

defineOnce("ce-rating", CeRating);

export { CeRating };
