// AUTO-GENERATED by scripts/generate-exports.ts — do not edit by hand.
// Source of truth: src/**/*.meta.json.


import { defineOnce } from "../core/index.js";
import { CeRecommendation } from "../components/recommendation/recommendation.js";

defineOnce("ce-recommendation", CeRecommendation);

export { CeRecommendation };
