// AUTO-GENERATED by scripts/generate-exports.ts — do not edit by hand.
// Source of truth: src/**/*.meta.json.


import { defineOnce } from "../core/index.js";
import { CeSection } from "../components/section/section.js";

defineOnce("ce-section", CeSection);

export { CeSection };
