// AUTO-GENERATED by scripts/generate-exports.ts — do not edit by hand.
// Source of truth: src/**/*.meta.json.


import { defineOnce } from "../core/index.js";
import { CeSegmented } from "../components/segmented/segmented.js";

defineOnce("ce-segmented", CeSegmented);

export { CeSegmented };
