// AUTO-GENERATED by scripts/generate-exports.ts — do not edit by hand.
// Source of truth: src/**/*.meta.json.


import { defineOnce } from "../core/index.js";
import { CeSelect } from "../components/select/select.js";

defineOnce("ce-select", CeSelect);

export { CeSelect };
