// AUTO-GENERATED by scripts/generate-exports.ts — do not edit by hand.
// Source of truth: src/**/*.meta.json.


import { defineOnce } from "../core/index.js";
import { CeShell } from "../components/shell/shell.js";

defineOnce("ce-shell", CeShell);

export { CeShell };
