// AUTO-GENERATED by scripts/generate-exports.ts — do not edit by hand.
// Source of truth: src/**/*.meta.json.


import { defineOnce } from "../core/index.js";
import { CeSkeleton } from "../components/skeleton/skeleton.js";

defineOnce("ce-skeleton", CeSkeleton);

export { CeSkeleton };
