// AUTO-GENERATED by scripts/generate-exports.ts — do not edit by hand.
// Source of truth: src/**/*.meta.json.


import { defineOnce } from "../core/index.js";
import { CeSourceCard } from "../components/source-card/source-card.js";

defineOnce("ce-source-card", CeSourceCard);

export { CeSourceCard };
