// AUTO-GENERATED by scripts/generate-exports.ts — do not edit by hand.
// Source of truth: src/**/*.meta.json.


import { defineOnce } from "../core/index.js";
import { CeSparkline } from "../components/sparkline/sparkline.js";

defineOnce("ce-sparkline", CeSparkline);

export { CeSparkline };
