// AUTO-GENERATED by scripts/generate-exports.ts — do not edit by hand.
// Source of truth: src/**/*.meta.json.


import { defineOnce } from "../core/index.js";
import { CeStack } from "../components/stack/stack.js";

defineOnce("ce-stack", CeStack);

export { CeStack };
