// AUTO-GENERATED by scripts/generate-exports.ts — do not edit by hand.
// Source of truth: src/**/*.meta.json.


import { defineOnce } from "../core/index.js";
import { CeStatGroup } from "../components/stat-group/stat-group.js";

defineOnce("ce-stat-group", CeStatGroup);

export { CeStatGroup };
