// AUTO-GENERATED by scripts/generate-exports.ts — do not edit by hand.
// Source of truth: src/**/*.meta.json.


import { defineOnce } from "../core/index.js";
import { CeStatusLight } from "../components/status-light/status-light.js";

defineOnce("ce-status-light", CeStatusLight);

export { CeStatusLight };
