// AUTO-GENERATED by scripts/generate-exports.ts — do not edit by hand.
// Source of truth: src/**/*.meta.json.


import { defineOnce } from "../core/index.js";
import { CeStopButton } from "../components/stop-button/stop-button.js";

defineOnce("ce-stop-button", CeStopButton);

export { CeStopButton };
