// AUTO-GENERATED by scripts/generate-exports.ts — do not edit by hand.
// Source of truth: src/**/*.meta.json.


import { defineOnce } from "../core/index.js";
import { CeStreamStatus } from "../components/stream-status/stream-status.js";

defineOnce("ce-stream-status", CeStreamStatus);

export { CeStreamStatus };
