// AUTO-GENERATED by scripts/generate-exports.ts — do not edit by hand.
// Source of truth: src/**/*.meta.json.


import { defineOnce } from "../core/index.js";
import { CeSuggestionChip } from "../components/suggestion-chip/suggestion-chip.js";

defineOnce("ce-suggestion-chip", CeSuggestionChip);

export { CeSuggestionChip };
