// AUTO-GENERATED by scripts/generate-exports.ts — do not edit by hand.
// Source of truth: src/**/*.meta.json.


import { defineOnce } from "../core/index.js";
import { CeTabs } from "../components/tabs/tabs.js";

defineOnce("ce-tabs", CeTabs);

export { CeTabs };
