// AUTO-GENERATED by scripts/generate-exports.ts — do not edit by hand.
// Source of truth: src/**/*.meta.json.


import { defineOnce } from "../core/index.js";
import { CeTextarea } from "../components/textarea/textarea.js";

defineOnce("ce-textarea", CeTextarea);

export { CeTextarea };
