// AUTO-GENERATED by scripts/generate-exports.ts — do not edit by hand.
// Source of truth: src/**/*.meta.json.


import { defineOnce } from "../core/index.js";
import { CeThemeSwitcher } from "../components/theme-switcher/theme-switcher.js";

defineOnce("ce-theme-switcher", CeThemeSwitcher);

export { CeThemeSwitcher };
