// AUTO-GENERATED by scripts/generate-exports.ts — do not edit by hand.
// Source of truth: src/**/*.meta.json.


import { defineOnce } from "../core/index.js";
import { CeTimeline } from "../components/timeline/timeline.js";

defineOnce("ce-timeline", CeTimeline);

export { CeTimeline };
