// AUTO-GENERATED by scripts/generate-exports.ts — do not edit by hand.
// Source of truth: src/**/*.meta.json.


import { defineOnce } from "../core/index.js";
import { CeToc } from "../components/toc/toc.js";

defineOnce("ce-toc", CeToc);

export { CeToc };
