// AUTO-GENERATED by scripts/generate-exports.ts — do not edit by hand.
// Source of truth: src/**/*.meta.json.


import { defineOnce } from "../core/index.js";
import { CeToggle } from "../components/toggle/toggle.js";

defineOnce("ce-toggle", CeToggle);

export { CeToggle };
