// AUTO-GENERATED by scripts/generate-exports.ts — do not edit by hand.
// Source of truth: src/**/*.meta.json.


import { defineOnce } from "../core/index.js";
import { CeToolCall } from "../components/tool-call/tool-call.js";

defineOnce("ce-tool-call", CeToolCall);

export { CeToolCall };
