// AUTO-GENERATED by scripts/generate-exports.ts — do not edit by hand.
// Source of truth: src/**/*.meta.json.


import { defineOnce } from "../core/index.js";
import { CeTooltip } from "../components/tooltip/tooltip.js";

defineOnce("ce-tooltip", CeTooltip);

export { CeTooltip };
