// AUTO-GENERATED by scripts/generate-exports.ts — do not edit by hand.
// Source of truth: src/**/*.meta.json.


import { defineOnce } from "../core/index.js";
import { CeTree } from "../components/tree/tree.js";

defineOnce("ce-tree", CeTree);

export { CeTree };
