// AUTO-GENERATED by scripts/generate-exports.ts — do not edit by hand.
// Source of truth: src/**/*.meta.json.


import { defineOnce } from "../core/index.js";
import { CeVerdict } from "../components/verdict/verdict.js";

defineOnce("ce-verdict", CeVerdict);

export { CeVerdict };
