/**
 * scripts/generate-skill.ts — regenerates the catalog and per-tag index inside
 * `skills/cec-consumer/references/` from the per-component meta files.
 *
 * Outputs:
 *   - `skills/cec-consumer/references/catalog.md` — slim per-category table,
 *     one row per component (tag, tier, goal).
 *   - `skills/cec-consumer/references/index.md`   — per-tag index with class,
 *     tier, group, stability, and a link to the canonical meta JSON.
 *
 * Both files are written whole; do not hand-edit. Run via `pnpm gen-skill`.
 * Idempotent. The `--check` flag exits non-zero on any drift.
 */

import { promises as fs } from "node:fs";
import path from "node:path";
import { fileURLToPath } from "node:url";
import {
  ComponentMetaSchema,
  type ComponentMeta,
} from "../src/meta/schema.js";

const __filename = fileURLToPath(import.meta.url);
const REPO_ROOT = path.resolve(path.dirname(__filename), "..");
const SRC_DIR = path.join(REPO_ROOT, "src");
const CATALOG_FILE = path.join(
  REPO_ROOT,
  "skills",
  "cec-consumer",
  "references",
  "catalog.md"
);
const INDEX_FILE = path.join(
  REPO_ROOT,
  "skills",
  "cec-consumer",
  "references",
  "index.md"
);

const CATEGORY_ORDER: ReadonlyArray<ComponentMeta["category"]> = [
  "ui",
  "lesson",
  "internal",
];

interface Loaded {
  meta: ComponentMeta;
  /** path of the source meta file relative to repo root, used in the index */
  source: string;
}

async function walk(dir: string): Promise<string[]> {
  const out: string[] = [];
  let entries: import("node:fs").Dirent[];
  try {
    entries = await fs.readdir(dir, { withFileTypes: true });
  } catch {
    return out;
  }
  for (const e of entries) {
    const full = path.join(dir, e.name);
    if (e.isDirectory()) out.push(...(await walk(full)));
    else if (e.isFile() && e.name.endsWith(".meta.json")) out.push(full);
  }
  return out;
}

async function loadAll(): Promise<Loaded[]> {
  const files = (await walk(SRC_DIR)).sort();
  const out: Loaded[] = [];
  for (const f of files) {
    const raw = await fs.readFile(f, "utf8");
    const meta = ComponentMetaSchema.parse(JSON.parse(raw));
    out.push({ meta, source: path.relative(REPO_ROOT, f) });
  }
  return out;
}

function sortItems(items: Loaded[]): Loaded[] {
  return items.slice().sort((a, b) => {
    const ca = CATEGORY_ORDER.indexOf(a.meta.category);
    const cb = CATEGORY_ORDER.indexOf(b.meta.category);
    if (ca !== cb) return ca - cb;
    const ga = (a.meta.tags?.[0] ?? "").localeCompare(b.meta.tags?.[0] ?? "");
    if (ga !== 0) return ga;
    return a.meta.tag.localeCompare(b.meta.tag);
  });
}

function groupByCategory(
  items: Loaded[]
): Map<ComponentMeta["category"], Loaded[]> {
  const map = new Map<ComponentMeta["category"], Loaded[]>();
  for (const cat of CATEGORY_ORDER) map.set(cat, []);
  for (const item of items) {
    map.get(item.meta.category)!.push(item);
  }
  return map;
}

const CATEGORY_LABEL: Record<ComponentMeta["category"], string> = {
  ui: "UI",
  lesson: "Lesson",
  internal: "Internal",
};

/** catalog.md — slim table, one row per component, grouped by category + tag[0]. */
function renderCatalog(items: Loaded[]): string {
  const lines: string[] = [];
  const grouped = groupByCategory(items);

  lines.push("# Component catalog");
  lines.push("");
  lines.push(
    "_Auto-generated by `pnpm gen-skill` from `src/**/*.meta.json`. Do not hand-edit._"
  );
  lines.push("");
  lines.push(`**Total components: ${items.length}**`);
  lines.push("");

  for (const cat of CATEGORY_ORDER) {
    const rows = grouped.get(cat) ?? [];
    if (rows.length === 0) continue;
    // Subgroup by tags[0]
    const subgroups = new Map<string, Loaded[]>();
    for (const r of rows) {
      const g = r.meta.tags?.[0] ?? "(ungrouped)";
      if (!subgroups.has(g)) subgroups.set(g, []);
      subgroups.get(g)!.push(r);
    }
    lines.push(`## ${CATEGORY_LABEL[cat]} (${rows.length})`);
    lines.push("");
    for (const [groupName, groupRows] of [...subgroups.entries()].sort(
      (a, b) => a[0].localeCompare(b[0])
    )) {
      if (subgroups.size > 1) {
        lines.push(`### ${groupName}`);
        lines.push("");
      }
      lines.push("| Tag | Tier | Goal |");
      lines.push("| --- | --- | --- |");
      for (const r of groupRows) {
        const tag = `\`${r.meta.tag}\``;
        const tier = r.meta.tier;
        const goal = r.meta.goal.replace(/\|/g, "\\|");
        lines.push(`| ${tag} | ${tier} | ${goal} |`);
      }
      lines.push("");
    }
  }

  lines.push(
    "Full per-component descriptors live in `src/**/*.meta.json` (also published to `dist/meta/<tag>.json` and `dist/meta/index.json`). Filter via `node scripts/components.mjs --help`."
  );
  lines.push("");
  return lines.join("\n");
}

/** index.md — one row per tag with links to source meta. */
function renderIndex(items: Loaded[]): string {
  const lines: string[] = [];
  const grouped = groupByCategory(items);
  lines.push("# Component index");
  lines.push("");
  lines.push(
    "_Auto-generated by `pnpm gen-skill` from `src/**/*.meta.json`. Do not hand-edit._"
  );
  lines.push("");
  lines.push(
    "Each row links to the canonical meta JSON. The same data ships in the npm tarball under `dist/meta/<tag>.json` and the bundle `dist/meta/index.json`. For a filtered programmatic read, use `node scripts/components.mjs`."
  );
  lines.push("");
  for (const cat of CATEGORY_ORDER) {
    const rows = grouped.get(cat) ?? [];
    if (rows.length === 0) continue;
    lines.push(`## ${CATEGORY_LABEL[cat]} (${rows.length})`);
    lines.push("");
    lines.push("| Tag | Class | Tier | Group | Stability | Meta |");
    lines.push("| --- | --- | --- | --- | --- | --- |");
    for (const r of rows) {
      const tag = `\`${r.meta.tag}\``;
      const cls = `\`${r.meta.className}\``;
      const group = r.meta.tags?.[0] ?? "—";
      // index.md lives at skills/cec-consumer/references/index.md — three ../ to reach repo root.
      const meta = `[\`${r.source}\`](../../../${r.source})`;
      lines.push(
        `| ${tag} | ${cls} | ${r.meta.tier} | ${group} | ${r.meta.stability} | ${meta} |`
      );
    }
    lines.push("");
  }
  return lines.join("\n");
}

async function writeIfChanged(file: string, content: string): Promise<boolean> {
  let prev: string | null = null;
  try {
    prev = await fs.readFile(file, "utf8");
  } catch {
    prev = null;
  }
  if (prev === content) return false;
  await fs.mkdir(path.dirname(file), { recursive: true });
  await fs.writeFile(file, content, "utf8");
  return true;
}

async function main(): Promise<void> {
  const checkMode = process.argv.includes("--check");

  const items = sortItems(await loadAll());
  if (items.length === 0) {
    console.log("[gen-skill] No meta files — nothing to do.");
    return;
  }

  const nextCatalog = renderCatalog(items);
  const nextIndex = renderIndex(items);

  if (checkMode) {
    const stale: string[] = [];
    let catalogPrev = "";
    try {
      catalogPrev = await fs.readFile(CATALOG_FILE, "utf8");
    } catch {
      catalogPrev = "";
    }
    if (catalogPrev !== nextCatalog)
      stale.push("skills/cec-consumer/references/catalog.md");
    let indexPrev = "";
    try {
      indexPrev = await fs.readFile(INDEX_FILE, "utf8");
    } catch {
      indexPrev = "";
    }
    if (indexPrev !== nextIndex)
      stale.push("skills/cec-consumer/references/index.md");
    if (stale.length) {
      console.error(
        `[gen-skill] OUT OF DATE — run \`pnpm gen-skill\` and commit:\n  - ${stale.join("\n  - ")}`
      );
      process.exit(1);
    }
    console.log(
      `[gen-skill] OK — skill in sync with ${items.length} meta file(s).`
    );
    return;
  }

  const catalogChanged = await writeIfChanged(CATALOG_FILE, nextCatalog);
  const indexChanged = await writeIfChanged(INDEX_FILE, nextIndex);

  console.log(
    `[gen-skill] ${items.length} component(s) · catalog.md ${catalogChanged ? "updated" : "unchanged"} · index.md ${indexChanged ? "updated" : "unchanged"}.`
  );
}

if (import.meta.url === `file://${process.argv[1]}`) {
  main().catch((e) => {
    console.error("[gen-skill] CRASH:", e);
    process.exit(2);
  });
}
