/**
 * scripts/generate-exports.ts — regenerates `src/index.ts`, `src/auto.ts`,
 * `src/entries/<name>.ts`, and `src/manifest.ts` from the per-component
 * `*.meta.json` source-of-truth files.
 *
 * Stage 1 behavior: when no meta files exist yet, the script prints a
 * skip warning and exits 0 — leaving the existing hand-written
 * `src/index.ts`, `src/auto.ts`, `src/entries/*` and `src/manifest.ts`
 * untouched. Stage 2 will populate meta files and activate generation.
 */

import { promises as fs } from "node:fs";
import path from "node:path";
import { fileURLToPath } from "node:url";
import {
  ComponentMetaSchema,
  type ComponentMeta,
} from "../src/meta/schema.js";

const __filename = fileURLToPath(import.meta.url);
const __dirname = path.dirname(__filename);
const REPO_ROOT = path.resolve(__dirname, "..");
const SRC_DIR = path.join(REPO_ROOT, "src");

const BANNER =
  "// AUTO-GENERATED by scripts/generate-exports.ts — do not edit by hand.\n" +
  "// Source of truth: src/**/*.meta.json.\n";

const CATEGORY_ORDER: ReadonlyArray<ComponentMeta["category"]> = [
  "ui",
  "lesson",
  "internal",
];

interface LoadedMeta {
  meta: ComponentMeta;
  /** filename stem (without .meta.json), used as the import subpath name */
  stem: string;
  /** "components" | "lesson" — which subtree the meta file lives under */
  subtree: "components" | "lesson";
  /** Names of `export type` / `export interface` declarations in the source. */
  exportedTypes: string[];
}

async function walk(dir: string): Promise<string[]> {
  const out: string[] = [];
  let entries: import("node:fs").Dirent[];
  try {
    entries = await fs.readdir(dir, { withFileTypes: true });
  } catch {
    return out;
  }
  for (const entry of entries) {
    const full = path.join(dir, entry.name);
    if (entry.isDirectory()) {
      out.push(...(await walk(full)));
    } else if (entry.isFile()) {
      out.push(full);
    }
  }
  return out;
}

/** Find top-level `export type Foo` / `export interface Foo` declarations
 *  in a component source file. We only match top-level (column-0) lines so
 *  inline `export type` inside namespaces or comments don't slip in. */
async function readExportedTypes(sourceFile: string): Promise<string[]> {
  let raw: string;
  try {
    raw = await fs.readFile(sourceFile, "utf8");
  } catch {
    return [];
  }
  const out: string[] = [];
  const re = /^export\s+(?:type|interface)\s+([A-Za-z_$][A-Za-z0-9_$]*)\b/gm;
  let m: RegExpExecArray | null;
  while ((m = re.exec(raw)) !== null) {
    out.push(m[1]);
  }
  return out;
}

async function loadAllMeta(): Promise<LoadedMeta[]> {
  const files = (await walk(SRC_DIR))
    .filter((p) => p.endsWith(".meta.json"))
    .sort();

  const out: LoadedMeta[] = [];
  for (const file of files) {
    const raw = await fs.readFile(file, "utf8");
    const json = JSON.parse(raw);
    const parsed = ComponentMetaSchema.parse(json);

    const stem = path.basename(file, ".meta.json");
    const dirName = path.basename(path.dirname(file));
    const grandDir = path.basename(path.dirname(path.dirname(file)));
    let subtree: "components" | "lesson";
    if (grandDir === "components" || dirName === "components") {
      subtree = "components";
    } else if (grandDir === "lesson" || dirName === "lesson") {
      subtree = "lesson";
    } else {
      throw new Error(
        `[gen-exports] Cannot determine subtree for ${file} — expected under src/components/ or src/lesson/.`
      );
    }
    const sourceFile = path.join(path.dirname(file), `${stem}.ts`);
    const exportedTypes = await readExportedTypes(sourceFile);
    out.push({ meta: parsed, stem, subtree, exportedTypes });
  }
  return out;
}

function sortMetas(metas: LoadedMeta[]): LoadedMeta[] {
  return [...metas].sort((a, b) => {
    const ca = CATEGORY_ORDER.indexOf(a.meta.category);
    const cb = CATEGORY_ORDER.indexOf(b.meta.category);
    if (ca !== cb) return ca - cb;
    return a.meta.tag.localeCompare(b.meta.tag);
  });
}

function importPathFor(item: LoadedMeta): string {
  // Nested layout target: ./components/<name>/<name>.js or ./lesson/<name>/<name>.js
  return `./${item.subtree}/${item.stem}/${item.stem}.js`;
}

function entryImportPathFor(item: LoadedMeta): string {
  // Used from inside src/entries/<name>.ts (one level below src/).
  return `../${item.subtree}/${item.stem}/${item.stem}.js`;
}

function renderIndex(metas: LoadedMeta[]): string {
  const lines: string[] = [BANNER];
  lines.push("");
  lines.push(
    "/**\n * Named exports of every component class shipped in this package.\n *\n * Importing this module does NOT auto-register tags — call `defineAll()`,\n * import a per-tag entry (e.g. `custom-elements-collection/hero`), or import\n * the side-effect `./auto` module to register them.\n */"
  );
  lines.push("");
  for (const item of metas) {
    const typeBits = item.exportedTypes
      .map((t) => `, type ${t}`)
      .join("");
    lines.push(
      `export { ${item.meta.className}${typeBits} } from "${importPathFor(item)}";`
    );
  }
  lines.push("");
  lines.push("// Core helpers (for consumers authoring their own components)");
  lines.push(`export { CecElement, defineOnce } from "./core/index.js";`);
  lines.push("");
  lines.push("// Manifest (machine-readable catalog + on-demand loader)");
  lines.push("export {");
  lines.push("  COMPONENTS,");
  lines.push("  UI_COMPONENTS,");
  lines.push("  LESSON_COMPONENTS,");
  lines.push("  INTERNAL_COMPONENTS,");
  lines.push("  loadOnDemand,");
  lines.push("  type Category,");
  lines.push("  type ComponentEntry,");
  lines.push(`} from "./manifest.js";`);
  lines.push("");
  lines.push("// Bulk registration");
  lines.push(`export { defineAll } from "./auto.js";`);
  lines.push("");
  return lines.join("\n");
}

function renderAuto(metas: LoadedMeta[]): string {
  const lines: string[] = [BANNER];
  lines.push("");
  lines.push(
    "/**\n * Side-effect module: registers every ce-* and lesson-* tag from this package.\n *\n *   import \"custom-elements-collection/auto\";\n *\n * Importing this module immediately calls `defineAll()`. Consumers who want\n * to register at a chosen point can `import { defineAll } from \"…\"` directly.\n */"
  );
  lines.push("");
  lines.push(`import { defineOnce } from "./core/index.js";`);
  for (const item of metas) {
    lines.push(
      `import { ${item.meta.className} } from "${importPathFor(item)}";`
    );
  }
  lines.push("");
  lines.push("export function defineAll(): void {");
  for (const item of metas) {
    lines.push(`  defineOnce("${item.meta.tag}", ${item.meta.className});`);
  }
  lines.push("}");
  lines.push("");
  lines.push("defineAll();");
  lines.push("");
  return lines.join("\n");
}

function renderEntry(item: LoadedMeta): string {
  // Per-tag entry: import the class, defineOnce it, re-export. Consumers can
  // import `custom-elements-collection/<stem>` to register a single tag.
  const lines: string[] = [BANNER];
  lines.push("");
  lines.push(`import { defineOnce } from "../core/index.js";`);
  lines.push(
    `import { ${item.meta.className} } from "${entryImportPathFor(item)}";`
  );
  lines.push("");
  lines.push(`defineOnce("${item.meta.tag}", ${item.meta.className});`);
  lines.push("");
  lines.push(`export { ${item.meta.className} };`);
  lines.push("");
  return lines.join("\n");
}

function renderManifest(metas: LoadedMeta[]): string {
  const lines: string[] = [BANNER];
  lines.push("");
  lines.push("/**");
  lines.push(" * Machine-readable catalog of every component shipped in this package.");
  lines.push(" *");
  lines.push(" * Consumers can use this for:");
  lines.push(" *   - build-time discovery (which tags exist?)");
  lines.push(" *   - docs generation");
  lines.push(" *   - dynamic on-demand loading (see `loadOnDemand` below)");
  lines.push(" */");
  lines.push("");
  lines.push(`export type Category = "ui" | "lesson" | "internal";`);
  lines.push("");
  lines.push("export interface ComponentEntry {");
  lines.push("  /** Short subpath name (also the import specifier after the package name). */");
  lines.push("  readonly name: string;");
  lines.push("  /** Registered custom-element tag name. */");
  lines.push("  readonly tag: string;");
  lines.push("  /** Exported class name. */");
  lines.push("  readonly className: string;");
  lines.push("  /** Subpath import specifier (e.g. \"custom-elements-collection/hero\"). */");
  lines.push("  readonly import: string;");
  lines.push("  /** One-line human-readable description. */");
  lines.push("  readonly description: string;");
  lines.push("  readonly category: Category;");
  lines.push("  /** Optional sub-group within the category (for sidebar sectioning). */");
  lines.push("  readonly group?: string;");
  lines.push("}");
  lines.push("");
  lines.push("export const COMPONENTS: ReadonlyArray<ComponentEntry> = [");
  for (const item of metas) {
    const group = item.meta.tags?.[0];
    const groupClause = group ? `, group: ${JSON.stringify(group)}` : "";
    const entry = `  { name: ${JSON.stringify(item.stem)}, tag: ${JSON.stringify(item.meta.tag)}, className: ${JSON.stringify(item.meta.className)}, import: ${JSON.stringify(`custom-elements-collection/${item.stem}`)}, category: ${JSON.stringify(item.meta.category)}${groupClause}, description: ${JSON.stringify(item.meta.description)} },`;
    lines.push(entry);
  }
  lines.push("];");
  lines.push("");
  lines.push("/**");
  lines.push(" * Dynamic on-demand loader — resolves a subset of components by tag or name");
  lines.push(" * via native ESM `import()`. Bundlers tree-shake the unused branches.");
  lines.push(" *");
  lines.push(" *   await loadOnDemand([\"ce-hero\", \"ce-kpi\"]);");
  lines.push(" *   await loadOnDemand(\"lesson-rule\");");
  lines.push(" */");
  lines.push("export async function loadOnDemand(");
  lines.push("  selection: string | ReadonlyArray<string>");
  lines.push("): Promise<void> {");
  lines.push("  const wanted = typeof selection === \"string\" ? [selection] : selection;");
  lines.push("  const set = new Set(wanted);");
  lines.push("  const matched = COMPONENTS.filter(");
  lines.push("    (c) => set.has(c.tag) || set.has(c.name)");
  lines.push("  );");
  lines.push("  await Promise.all(matched.map((c) => import(/* @vite-ignore */ c.import)));");
  lines.push("}");
  lines.push("");
  lines.push("/** Filter helper: all UI components. */");
  lines.push("export const UI_COMPONENTS = COMPONENTS.filter((c) => c.category === \"ui\");");
  lines.push("");
  lines.push("/** Filter helper: all lesson components. */");
  lines.push("export const LESSON_COMPONENTS = COMPONENTS.filter((c) => c.category === \"lesson\");");
  lines.push("");
  lines.push("/** Filter helper: all internal / layout components. */");
  lines.push("export const INTERNAL_COMPONENTS = COMPONENTS.filter((c) => c.category === \"internal\");");
  lines.push("");
  return lines.join("\n");
}

async function writeIfChanged(file: string, content: string): Promise<boolean> {
  let prev: string | null = null;
  try {
    prev = await fs.readFile(file, "utf8");
  } catch {
    prev = null;
  }
  if (prev === content) return false;
  await fs.mkdir(path.dirname(file), { recursive: true });
  await fs.writeFile(file, content, "utf8");
  return true;
}

/**
 * Sync the `exports` map in package.json with the set of generated entries.
 *
 * Keeps every non-component export untouched (".", "./auto", "./manifest",
 * "./*.css", any unknown subpath) and ensures one `./<stem>` block per
 * component pointing at `./dist/entries/<stem>.{d.ts,js}`. Stale component
 * subpaths whose meta no longer exists are removed.
 *
 * Returns true when package.json was rewritten.
 */
async function syncPackageExports(stems: ReadonlyArray<string>): Promise<boolean> {
  const pkgFile = path.join(REPO_ROOT, "package.json");
  const raw = await fs.readFile(pkgFile, "utf8");
  const pkg = JSON.parse(raw) as {
    exports?: Record<string, unknown>;
    [k: string]: unknown;
  };
  const exportsMap: Record<string, unknown> = { ...(pkg.exports ?? {}) };
  const stemSet = new Set(stems);

  // Drop stale component subpaths (those whose entry block points at
  // ./dist/entries/<stem>.js but stem no longer exists in meta).
  for (const key of Object.keys(exportsMap)) {
    if (!key.startsWith("./") || key === ".") continue;
    if (key.endsWith(".css")) continue;
    if (key === "./auto" || key === "./manifest") continue;
    const stem = key.slice(2);
    if (stem.includes("/")) continue; // future nested subpaths
    if (!stemSet.has(stem)) {
      delete exportsMap[key];
    }
  }

  // Ensure each known stem is present with the canonical block.
  for (const stem of stems) {
    const key = `./${stem}`;
    exportsMap[key] = {
      types: `./dist/entries/${stem}.d.ts`,
      import: `./dist/entries/${stem}.js`,
    };
  }

  // Meta subpaths — opt-in for consumers that want machine-readable API
  // descriptors without paying any runtime cost. The `./meta/*.json` wildcard
  // resolves to the per-tag file emitted by the vite copy-meta plugin; the
  // `./meta` bare specifier resolves to the combined bundle.
  exportsMap["./meta/*.json"] = "./dist/meta/*.json";
  exportsMap["./meta"] = "./dist/meta/index.json";

  // Registry subpaths — LLM-tool-use-shaped projection (see ADR-007). The
  // `./registry` bare specifier resolves to the full registry; the
  // `./registry/*.json` wildcard resolves to filtered views (by-tier,
  // by-group, by-category) and per-tag single-component descriptors.
  exportsMap["./registry"] = "./dist/registry.json";
  exportsMap["./registry/*.json"] = "./dist/registry/*.json";

  // v2 (ADR-015) — relations graph, conformance audit, and the
  // machine-readable mirror of meta-fields-registry.md.
  exportsMap["./relations"] = "./dist/relations.json";
  exportsMap["./conformance"] = "./dist/conformance.json";
  exportsMap["./meta-fields-registry"] = "./dist/meta-fields-registry.json";

  // Sort exports for deterministic diffs: ".", "./auto", "./manifest" first;
  // tokens (./*.css) next; meta subpaths next; per-component subpaths last.
  const ordered: Record<string, unknown> = {};
  const reserved = new Set([
    ".",
    "./auto",
    "./manifest",
    "./meta",
    "./meta/*.json",
    "./registry",
    "./registry/*.json",
    "./relations",
    "./conformance",
    "./meta-fields-registry",
  ]);
  for (const key of [".", "./auto", "./manifest"]) {
    if (key in exportsMap) ordered[key] = exportsMap[key];
  }
  const cssKeys = Object.keys(exportsMap)
    .filter((k) => k.endsWith(".css"))
    .sort();
  for (const k of cssKeys) ordered[k] = exportsMap[k];
  for (const key of [
    "./meta",
    "./meta/*.json",
    "./registry",
    "./registry/*.json",
    "./relations",
    "./conformance",
    "./meta-fields-registry",
  ]) {
    if (key in exportsMap) ordered[key] = exportsMap[key];
  }
  const componentKeys = Object.keys(exportsMap)
    .filter((k) => !reserved.has(k) && !k.endsWith(".css"))
    .sort();
  for (const k of componentKeys) ordered[k] = exportsMap[k];

  pkg.exports = ordered;
  const next = JSON.stringify(pkg, null, 2) + "\n";
  if (next === raw) return false;
  await fs.writeFile(pkgFile, next, "utf8");
  return true;
}

export async function generateAll(opts?: { publishOnly?: boolean }): Promise<{
  written: string[];
  count: number;
}> {
  const all = await loadAllMeta();
  if (all.length === 0) {
    return { written: [], count: 0 };
  }

  const filtered = opts?.publishOnly
    ? all.filter((i) => i.meta.category !== "internal")
    : all;

  const sorted = sortMetas(filtered);
  const written: string[] = [];

  if (opts?.publishOnly) {
    // Publish manifest only — separate file, never touches the main outputs.
    const file = path.join(SRC_DIR, "manifest.publish.ts");
    if (await writeIfChanged(file, renderManifest(sorted))) {
      written.push(file);
    }
    return { written, count: sorted.length };
  }

  // index.ts
  if (
    await writeIfChanged(path.join(SRC_DIR, "index.ts"), renderIndex(sorted))
  ) {
    written.push(path.join(SRC_DIR, "index.ts"));
  }
  // auto.ts
  if (
    await writeIfChanged(path.join(SRC_DIR, "auto.ts"), renderAuto(sorted))
  ) {
    written.push(path.join(SRC_DIR, "auto.ts"));
  }
  // entries/<name>.ts
  const entriesDir = path.join(SRC_DIR, "entries");
  for (const item of sorted) {
    const file = path.join(entriesDir, `${item.stem}.ts`);
    if (await writeIfChanged(file, renderEntry(item))) {
      written.push(file);
    }
  }
  // manifest.ts
  if (
    await writeIfChanged(
      path.join(SRC_DIR, "manifest.ts"),
      renderManifest(sorted)
    )
  ) {
    written.push(path.join(SRC_DIR, "manifest.ts"));
  }
  // package.json exports map
  if (await syncPackageExports(sorted.map((i) => i.stem))) {
    written.push(path.join(REPO_ROOT, "package.json"));
  }

  return { written, count: sorted.length };
}

async function main(): Promise<void> {
  const all = await loadAllMeta();
  if (all.length === 0) {
    console.log(
      "[gen-exports] No meta files yet — skipping; existing hand-written src/index.ts, src/auto.ts, src/entries/* are untouched."
    );
    process.exit(0);
  }

  const { written, count } = await generateAll();
  console.log(
    `[gen-exports] OK — generated outputs from ${count} meta file(s); ${written.length} file(s) updated.`
  );
  for (const f of written) {
    console.log(`  + ${path.relative(REPO_ROOT, f)}`);
  }
}

if (import.meta.url === `file://${process.argv[1]}`) {
  main().catch((e) => {
    console.error("[gen-exports] CRASH:", e);
    process.exit(2);
  });
}
