/**
 * scripts/generate-skill.ts — regenerates the catalog block inside
 * `skill/SKILL.md` and the per-tag index at `skill/references/index.md`
 * from the per-component meta files. Everything outside the
 * `<!-- BEGIN AUTO-GENERATED CATALOG -->` ... `<!-- END AUTO-GENERATED CATALOG -->`
 * markers in SKILL.md is hand-authored and untouched.
 *
 * Run via `pnpm gen-skill`. Idempotent.
 */

import { promises as fs } from "node:fs";
import path from "node:path";
import { fileURLToPath } from "node:url";
import {
  ComponentMetaSchema,
  type ComponentMeta,
} from "../src/meta/schema.js";

const __filename = fileURLToPath(import.meta.url);
const REPO_ROOT = path.resolve(path.dirname(__filename), "..");
const SRC_DIR = path.join(REPO_ROOT, "src");
const SKILL_FILE = path.join(REPO_ROOT, "skill", "SKILL.md");
const INDEX_FILE = path.join(REPO_ROOT, "skill", "references", "index.md");

const BEGIN = "<!-- BEGIN AUTO-GENERATED CATALOG -->";
const END = "<!-- END AUTO-GENERATED CATALOG -->";

const CATEGORY_ORDER: ReadonlyArray<ComponentMeta["category"]> = [
  "ui",
  "lesson",
  "internal",
];

interface Loaded {
  meta: ComponentMeta;
  /** path of the source meta file relative to repo root, used in the index */
  source: string;
}

async function walk(dir: string): Promise<string[]> {
  const out: string[] = [];
  let entries: import("node:fs").Dirent[];
  try {
    entries = await fs.readdir(dir, { withFileTypes: true });
  } catch {
    return out;
  }
  for (const e of entries) {
    const full = path.join(dir, e.name);
    if (e.isDirectory()) out.push(...(await walk(full)));
    else if (e.isFile() && e.name.endsWith(".meta.json")) out.push(full);
  }
  return out;
}

async function loadAll(): Promise<Loaded[]> {
  const files = (await walk(SRC_DIR)).sort();
  const out: Loaded[] = [];
  for (const f of files) {
    const raw = await fs.readFile(f, "utf8");
    const meta = ComponentMetaSchema.parse(JSON.parse(raw));
    out.push({ meta, source: path.relative(REPO_ROOT, f) });
  }
  return out;
}

function sortItems(items: Loaded[]): Loaded[] {
  return items.slice().sort((a, b) => {
    const ca = CATEGORY_ORDER.indexOf(a.meta.category);
    const cb = CATEGORY_ORDER.indexOf(b.meta.category);
    if (ca !== cb) return ca - cb;
    const ga = (a.meta.tags?.[0] ?? "").localeCompare(b.meta.tags?.[0] ?? "");
    if (ga !== 0) return ga;
    return a.meta.tag.localeCompare(b.meta.tag);
  });
}

function groupByCategory(
  items: Loaded[]
): Map<ComponentMeta["category"], Loaded[]> {
  const map = new Map<ComponentMeta["category"], Loaded[]>();
  for (const cat of CATEGORY_ORDER) map.set(cat, []);
  for (const item of items) {
    map.get(item.meta.category)!.push(item);
  }
  return map;
}

const CATEGORY_LABEL: Record<ComponentMeta["category"], string> = {
  ui: "UI",
  lesson: "Lesson",
  internal: "Internal",
};

/** SKILL.md catalog block — slim table, one row per component. */
function renderCatalog(items: Loaded[]): string {
  const lines: string[] = [];
  const grouped = groupByCategory(items);

  lines.push(BEGIN);
  lines.push("");
  lines.push(
    "_Auto-generated by `pnpm gen-skill` from `src/**/*.meta.json`. Do not hand-edit this block._"
  );
  lines.push("");
  lines.push(`**Total components: ${items.length}**`);
  lines.push("");

  for (const cat of CATEGORY_ORDER) {
    const rows = grouped.get(cat) ?? [];
    if (rows.length === 0) continue;
    // Subgroup by tags[0]
    const subgroups = new Map<string, Loaded[]>();
    for (const r of rows) {
      const g = r.meta.tags?.[0] ?? "(ungrouped)";
      if (!subgroups.has(g)) subgroups.set(g, []);
      subgroups.get(g)!.push(r);
    }
    lines.push(`### ${CATEGORY_LABEL[cat]} (${rows.length})`);
    lines.push("");
    for (const [groupName, groupRows] of [...subgroups.entries()].sort(
      (a, b) => a[0].localeCompare(b[0])
    )) {
      if (subgroups.size > 1) {
        lines.push(`**${groupName}**`);
        lines.push("");
      }
      lines.push("| Tag | Tier | Goal |");
      lines.push("| --- | --- | --- |");
      for (const r of groupRows) {
        const tag = `\`${r.meta.tag}\``;
        const tier = r.meta.tier;
        const goal = r.meta.goal.replace(/\|/g, "\\|");
        lines.push(`| ${tag} | ${tier} | ${goal} |`);
      }
      lines.push("");
    }
  }

  lines.push(
    "Full per-component descriptors live in `src/**/*.meta.json` (also published to `dist/meta/<tag>.json` and `dist/meta/index.json`). Filter via `node skill/scripts/components.mjs --help`."
  );
  lines.push("");
  lines.push(END);
  return lines.join("\n");
}

/** references/index.md — one row per tag with links to source meta. */
function renderIndex(items: Loaded[]): string {
  const lines: string[] = [];
  const grouped = groupByCategory(items);
  lines.push("# Component index");
  lines.push("");
  lines.push(
    "_Auto-generated by `pnpm gen-skill` from `src/**/*.meta.json`. Do not hand-edit._"
  );
  lines.push("");
  lines.push(
    "Each row links to the canonical meta JSON. The same data ships in the npm tarball under `dist/meta/<tag>.json` and the bundle `dist/meta/index.json`. For a filtered programmatic read, use `node skill/scripts/components.mjs`."
  );
  lines.push("");
  for (const cat of CATEGORY_ORDER) {
    const rows = grouped.get(cat) ?? [];
    if (rows.length === 0) continue;
    lines.push(`## ${CATEGORY_LABEL[cat]} (${rows.length})`);
    lines.push("");
    lines.push("| Tag | Class | Tier | Group | Stability | Meta |");
    lines.push("| --- | --- | --- | --- | --- | --- |");
    for (const r of rows) {
      const tag = `\`${r.meta.tag}\``;
      const cls = `\`${r.meta.className}\``;
      const group = r.meta.tags?.[0] ?? "—";
      const meta = `[\`${r.source}\`](../../${r.source})`;
      lines.push(
        `| ${tag} | ${cls} | ${r.meta.tier} | ${group} | ${r.meta.stability} | ${meta} |`
      );
    }
    lines.push("");
  }
  return lines.join("\n");
}

function replaceBlock(prev: string, fresh: string): string {
  const start = prev.indexOf(BEGIN);
  const end = prev.indexOf(END);
  if (start === -1 || end === -1 || end < start) {
    throw new Error(
      `[gen-skill] SKILL.md is missing the AUTO-GENERATED CATALOG markers.`
    );
  }
  const before = prev.slice(0, start);
  const after = prev.slice(end + END.length);
  return before + fresh + after;
}

async function writeIfChanged(file: string, content: string): Promise<boolean> {
  let prev: string | null = null;
  try {
    prev = await fs.readFile(file, "utf8");
  } catch {
    prev = null;
  }
  if (prev === content) return false;
  await fs.mkdir(path.dirname(file), { recursive: true });
  await fs.writeFile(file, content, "utf8");
  return true;
}

async function main(): Promise<void> {
  const checkMode = process.argv.includes("--check");

  const items = sortItems(await loadAll());
  if (items.length === 0) {
    console.log("[gen-skill] No meta files — nothing to do.");
    return;
  }

  // SKILL.md catalog block
  const catalog = renderCatalog(items);
  let skillPrev = "";
  try {
    skillPrev = await fs.readFile(SKILL_FILE, "utf8");
  } catch {
    throw new Error(
      `[gen-skill] ${SKILL_FILE} not found. Create it (with the catalog markers) before running this script.`
    );
  }
  const nextSkill = replaceBlock(skillPrev, catalog);
  const nextIndex = renderIndex(items);

  if (checkMode) {
    const stale: string[] = [];
    if (skillPrev !== nextSkill) stale.push("skill/SKILL.md");
    let indexPrev = "";
    try {
      indexPrev = await fs.readFile(INDEX_FILE, "utf8");
    } catch {
      indexPrev = "";
    }
    if (indexPrev !== nextIndex) stale.push("skill/references/index.md");
    if (stale.length) {
      console.error(
        `[gen-skill] OUT OF DATE — run \`pnpm gen-skill\` and commit:\n  - ${stale.join("\n  - ")}`
      );
      process.exit(1);
    }
    console.log(
      `[gen-skill] OK — skill in sync with ${items.length} meta file(s).`
    );
    return;
  }

  const skillChanged = await writeIfChanged(SKILL_FILE, nextSkill);
  const indexChanged = await writeIfChanged(INDEX_FILE, nextIndex);

  console.log(
    `[gen-skill] ${items.length} component(s) · SKILL.md ${skillChanged ? "updated" : "unchanged"} · references/index.md ${indexChanged ? "updated" : "unchanged"}.`
  );
}

if (import.meta.url === `file://${process.argv[1]}`) {
  main().catch((e) => {
    console.error("[gen-skill] CRASH:", e);
    process.exit(2);
  });
}
