// AUTO-GENERATED by scripts/generate-exports.ts — do not edit by hand.
// Source of truth: src/**/*.meta.json.


/**
 * Side-effect module: registers every ce-* and lesson-* tag from this package.
 *
 *   import "custom-elements-collection/auto";
 *
 * Importing this module immediately calls `defineAll()`. Consumers who want
 * to register at a chosen point can `import { defineAll } from "…"` directly.
 */

import { defineOnce } from "./core/index.js";
import { CeAbbr } from "./components/abbr/abbr.js";
import { CeBadge } from "./components/badge/badge.js";
import { CeBarChart } from "./components/bar-chart/bar-chart.js";
import { CeBookmark } from "./components/bookmark/bookmark.js";
import { CeButton } from "./components/button/button.js";
import { CeCallout } from "./components/callout/callout.js";
import { CeCard } from "./components/card/card.js";
import { CeChart } from "./components/chart/chart.js";
import { CeChatBubble } from "./components/chat-bubble/chat-bubble.js";
import { CeCheckbox } from "./components/checkbox/checkbox.js";
import { CeChecklist } from "./components/checklist/checklist.js";
import { CeChip } from "./components/chip/chip.js";
import { CeCitation } from "./components/citation/citation.js";
import { CeClock } from "./components/clock/clock.js";
import { CeCode } from "./components/code/code.js";
import { CeComment } from "./components/comment/comment.js";
import { CeCompare } from "./components/compare/compare.js";
import { CeConfirm } from "./components/confirm/confirm.js";
import { CeCopyButton } from "./components/copy-button/copy-button.js";
import { CeCounter } from "./components/counter/counter.js";
import { CeCursor } from "./components/cursor/cursor.js";
import { CeDecisionTree } from "./components/decision-tree/decision-tree.js";
import { CeDetails } from "./components/details/details.js";
import { CeDiff } from "./components/diff/diff.js";
import { CeDismiss } from "./components/dismiss/dismiss.js";
import { CeDonut } from "./components/donut/donut.js";
import { CeExample } from "./components/example/example.js";
import { CeFeatureCard } from "./components/feature-card/feature-card.js";
import { CeFeedbackBar } from "./components/feedback-bar/feedback-bar.js";
import { CeFeedbackExport } from "./components/feedback-export/feedback-export.js";
import { CeFeedbackHeatmap } from "./components/feedback-heatmap/feedback-heatmap.js";
import { CeFeedbackSink } from "./components/feedback-sink/feedback-sink.js";
import { CeFeedbackSummary } from "./components/feedback-summary/feedback-summary.js";
import { CeFileCard } from "./components/file-card/file-card.js";
import { CeFilterBar } from "./components/filter-bar/filter-bar.js";
import { CeFlow } from "./components/flow/flow.js";
import { CeGauge } from "./components/gauge/gauge.js";
import { CeGrid } from "./components/grid/grid.js";
import { CeHeatmap } from "./components/heatmap/heatmap.js";
import { CeHero } from "./components/hero/hero.js";
import { CeImage } from "./components/image/image.js";
import { CeInput } from "./components/input/input.js";
import { CeJson } from "./components/json/json.js";
import { CeKeyValue } from "./components/key-value/key-value.js";
import { CeKpi } from "./components/kpi/kpi.js";
import { CePersona } from "./components/persona/persona.js";
import { CeProgress } from "./components/progress/progress.js";
import { CeRating } from "./components/rating/rating.js";
import { CeRetryButton } from "./components/retry-button/retry-button.js";
import { CeSection } from "./components/section/section.js";
import { CeShell } from "./components/shell/shell.js";
import { CeSkeleton } from "./components/skeleton/skeleton.js";
import { CeSparkline } from "./components/sparkline/sparkline.js";
import { CeStatGroup } from "./components/stat-group/stat-group.js";
import { CeStatusLight } from "./components/status-light/status-light.js";
import { CeTable } from "./components/table/table.js";
import { CeTextarea } from "./components/textarea/textarea.js";
import { CeThinking } from "./components/thinking/thinking.js";
import { CeTimeline } from "./components/timeline/timeline.js";
import { CeToc } from "./components/toc/toc.js";
import { CeToggle } from "./components/toggle/toggle.js";
import { CeToolCall } from "./components/tool-call/tool-call.js";
import { CeVerdict } from "./components/verdict/verdict.js";
import { LessonAudio } from "./lesson/lesson-audio/lesson-audio.js";
import { LessonFrame } from "./lesson/lesson-frame/lesson-frame.js";
import { LessonGap } from "./lesson/lesson-gap/lesson-gap.js";
import { LessonQuickfire } from "./lesson/lesson-quickfire/lesson-quickfire.js";
import { LessonQuiz } from "./lesson/lesson-quiz/lesson-quiz.js";
import { LessonRule } from "./lesson/lesson-rule/lesson-rule.js";
import { CeDocsLayout } from "./components/docs-layout/docs-layout.js";
import { CeNavList } from "./components/nav-list/nav-list.js";
import { CeThemeSwitcher } from "./components/theme-switcher/theme-switcher.js";

export function defineAll(): void {
  defineOnce("ce-abbr", CeAbbr);
  defineOnce("ce-badge", CeBadge);
  defineOnce("ce-bar-chart", CeBarChart);
  defineOnce("ce-bookmark", CeBookmark);
  defineOnce("ce-button", CeButton);
  defineOnce("ce-callout", CeCallout);
  defineOnce("ce-card", CeCard);
  defineOnce("ce-chart", CeChart);
  defineOnce("ce-chat-bubble", CeChatBubble);
  defineOnce("ce-checkbox", CeCheckbox);
  defineOnce("ce-checklist", CeChecklist);
  defineOnce("ce-chip", CeChip);
  defineOnce("ce-citation", CeCitation);
  defineOnce("ce-clock", CeClock);
  defineOnce("ce-code", CeCode);
  defineOnce("ce-comment", CeComment);
  defineOnce("ce-compare", CeCompare);
  defineOnce("ce-confirm", CeConfirm);
  defineOnce("ce-copy-button", CeCopyButton);
  defineOnce("ce-counter", CeCounter);
  defineOnce("ce-cursor", CeCursor);
  defineOnce("ce-decision-tree", CeDecisionTree);
  defineOnce("ce-details", CeDetails);
  defineOnce("ce-diff", CeDiff);
  defineOnce("ce-dismiss", CeDismiss);
  defineOnce("ce-donut", CeDonut);
  defineOnce("ce-example", CeExample);
  defineOnce("ce-feature-card", CeFeatureCard);
  defineOnce("ce-feedback-bar", CeFeedbackBar);
  defineOnce("ce-feedback-export", CeFeedbackExport);
  defineOnce("ce-feedback-heatmap", CeFeedbackHeatmap);
  defineOnce("ce-feedback-sink", CeFeedbackSink);
  defineOnce("ce-feedback-summary", CeFeedbackSummary);
  defineOnce("ce-file-card", CeFileCard);
  defineOnce("ce-filter-bar", CeFilterBar);
  defineOnce("ce-flow", CeFlow);
  defineOnce("ce-gauge", CeGauge);
  defineOnce("ce-grid", CeGrid);
  defineOnce("ce-heatmap", CeHeatmap);
  defineOnce("ce-hero", CeHero);
  defineOnce("ce-image", CeImage);
  defineOnce("ce-input", CeInput);
  defineOnce("ce-json", CeJson);
  defineOnce("ce-key-value", CeKeyValue);
  defineOnce("ce-kpi", CeKpi);
  defineOnce("ce-persona", CePersona);
  defineOnce("ce-progress", CeProgress);
  defineOnce("ce-rating", CeRating);
  defineOnce("ce-retry-button", CeRetryButton);
  defineOnce("ce-section", CeSection);
  defineOnce("ce-shell", CeShell);
  defineOnce("ce-skeleton", CeSkeleton);
  defineOnce("ce-sparkline", CeSparkline);
  defineOnce("ce-stat-group", CeStatGroup);
  defineOnce("ce-status-light", CeStatusLight);
  defineOnce("ce-table", CeTable);
  defineOnce("ce-textarea", CeTextarea);
  defineOnce("ce-thinking", CeThinking);
  defineOnce("ce-timeline", CeTimeline);
  defineOnce("ce-toc", CeToc);
  defineOnce("ce-toggle", CeToggle);
  defineOnce("ce-tool-call", CeToolCall);
  defineOnce("ce-verdict", CeVerdict);
  defineOnce("lesson-audio", LessonAudio);
  defineOnce("lesson-frame", LessonFrame);
  defineOnce("lesson-gap", LessonGap);
  defineOnce("lesson-quickfire", LessonQuickfire);
  defineOnce("lesson-quiz", LessonQuiz);
  defineOnce("lesson-rule", LessonRule);
  defineOnce("ce-docs-layout", CeDocsLayout);
  defineOnce("ce-nav-list", CeNavList);
  defineOnce("ce-theme-switcher", CeThemeSwitcher);
}

defineAll();
