// AUTO-GENERATED by scripts/generate-exports.ts — do not edit by hand.
// Source of truth: src/**/*.meta.json.


/**
 * Named exports of every component class shipped in this package.
 *
 * Importing this module does NOT auto-register tags — call `defineAll()`,
 * import a per-tag entry (e.g. `custom-elements-collection/hero`), or import
 * the side-effect `./auto` module to register them.
 */

export { CeAbbr } from "./components/abbr/abbr.js";
export { CeBadge } from "./components/badge/badge.js";
export { CeBarChart, type BarRow } from "./components/bar-chart/bar-chart.js";
export { CeBarRow, type ValueDisplay } from "./components/bar-row/bar-row.js";
export { CeBookmark, type CeBookmarkSize } from "./components/bookmark/bookmark.js";
export { CeButton } from "./components/button/button.js";
export { CeCallout, type CalloutType } from "./components/callout/callout.js";
export { CeCard } from "./components/card/card.js";
export { CeChart } from "./components/chart/chart.js";
export { CeChatBubble, type CeChatRole } from "./components/chat-bubble/chat-bubble.js";
export { CeCheckItem } from "./components/check-item/check-item.js";
export { CeCheckbox } from "./components/checkbox/checkbox.js";
export { CeChecklist, type CeChecklistItem } from "./components/checklist/checklist.js";
export { CeChip } from "./components/chip/chip.js";
export { CeCitation } from "./components/citation/citation.js";
export { CeClock } from "./components/clock/clock.js";
export { CeCode } from "./components/code/code.js";
export { CeComment, type CeCommentSubmitOn } from "./components/comment/comment.js";
export { CeCompare } from "./components/compare/compare.js";
export { CeConfirm } from "./components/confirm/confirm.js";
export { CeCopyButton } from "./components/copy-button/copy-button.js";
export { CeCounter } from "./components/counter/counter.js";
export { CeCursor, type CeCursorShape } from "./components/cursor/cursor.js";
export { CeDecisionTree, type DecisionBranch } from "./components/decision-tree/decision-tree.js";
export { CeDetails } from "./components/details/details.js";
export { CeDiff } from "./components/diff/diff.js";
export { CeDismiss, type CeDismissSize } from "./components/dismiss/dismiss.js";
export { CeDonut } from "./components/donut/donut.js";
export { CeExample, type ExampleType } from "./components/example/example.js";
export { CeFeatureCard } from "./components/feature-card/feature-card.js";
export { CeFeedbackBar, type CeFeedbackBarLayout } from "./components/feedback-bar/feedback-bar.js";
export { CeFeedbackExport, type CeExportFormat, type CeExportLayout } from "./components/feedback-export/feedback-export.js";
export { CeFeedbackHeatmap } from "./components/feedback-heatmap/feedback-heatmap.js";
export { CeFeedbackSink, type CeFeedbackTransport, type CeFeedbackOfflineFallback, type FeedbackEvent, type ItemState, type SubjectState, type CeFeedbackTransportImpl } from "./components/feedback-sink/feedback-sink.js";
export { CeFeedbackSummary, type CeSummarySection } from "./components/feedback-summary/feedback-summary.js";
export { CeFileCard } from "./components/file-card/file-card.js";
export { CeFilterBar, type FilterOption } from "./components/filter-bar/filter-bar.js";
export { CeFlow, type FlowStep } from "./components/flow/flow.js";
export { CeFlowStep } from "./components/flow-step/flow-step.js";
export { CeGauge } from "./components/gauge/gauge.js";
export { CeGrid } from "./components/grid/grid.js";
export { CeHeatCell } from "./components/heat-cell/heat-cell.js";
export { CeHeatRow } from "./components/heat-row/heat-row.js";
export { CeHeatmap, type CellInput } from "./components/heatmap/heatmap.js";
export { CeHero } from "./components/hero/hero.js";
export { CeImage } from "./components/image/image.js";
export { CeInput } from "./components/input/input.js";
export { CeJson } from "./components/json/json.js";
export { CeKeyValue } from "./components/key-value/key-value.js";
export { CeKpi } from "./components/kpi/kpi.js";
export { CeKv } from "./components/kv/kv.js";
export { CePersona } from "./components/persona/persona.js";
export { CePlot, type PlotPoint, type PlotSeries, type PlotFormat } from "./components/plot/plot.js";
export { CePricingTier, type PricingFeature } from "./components/pricing-tier/pricing-tier.js";
export { CeProgress } from "./components/progress/progress.js";
export { CeProgressList } from "./components/progress-list/progress-list.js";
export { CeQr, type QrResult } from "./components/qr/qr.js";
export { CeQuote, type QuoteVariant } from "./components/quote/quote.js";
export { CeRadioGroup, type RadioOption } from "./components/radio-group/radio-group.js";
export { CeRating, type CeRatingMode, type CeRatingSize, type CeRatingValue } from "./components/rating/rating.js";
export { CeRecommendation, type RecommendationPriority } from "./components/recommendation/recommendation.js";
export { CeRetryButton, type CeRetryVariant } from "./components/retry-button/retry-button.js";
export { CeScore, type ScoreTier } from "./components/score/score.js";
export { CeSection } from "./components/section/section.js";
export { CeShell } from "./components/shell/shell.js";
export { CeSkeleton } from "./components/skeleton/skeleton.js";
export { CeSparkline } from "./components/sparkline/sparkline.js";
export { CeStatGroup } from "./components/stat-group/stat-group.js";
export { CeStatusLight, type CeStatusLightState } from "./components/status-light/status-light.js";
export { CeStep, type StepState } from "./components/step/step.js";
export { CeSteps, type StepItem } from "./components/steps/steps.js";
export { CeTable } from "./components/table/table.js";
export { CeTabs, type TabItem } from "./components/tabs/tabs.js";
export { CeTextarea } from "./components/textarea/textarea.js";
export { CeThinking, type CeThinkingVariant } from "./components/thinking/thinking.js";
export { CeTimeline, type TimelineItem } from "./components/timeline/timeline.js";
export { CeToc, type TocEntry } from "./components/toc/toc.js";
export { CeToggle } from "./components/toggle/toggle.js";
export { CeToolCall, type CeToolCallStatus } from "./components/tool-call/tool-call.js";
export { CeVerdict, type VerdictType } from "./components/verdict/verdict.js";
export { LessonAudio } from "./lesson/lesson-audio/lesson-audio.js";
export { LessonCompare } from "./lesson/lesson-compare/lesson-compare.js";
export { LessonConfidence } from "./lesson/lesson-confidence/lesson-confidence.js";
export { LessonFrame } from "./lesson/lesson-frame/lesson-frame.js";
export { LessonGap } from "./lesson/lesson-gap/lesson-gap.js";
export { LessonHint } from "./lesson/lesson-hint/lesson-hint.js";
export { LessonMatch } from "./lesson/lesson-match/lesson-match.js";
export { LessonMyth } from "./lesson/lesson-myth/lesson-myth.js";
export { LessonNote } from "./lesson/lesson-note/lesson-note.js";
export { LessonQuickfire, type QuickfireRound } from "./lesson/lesson-quickfire/lesson-quickfire.js";
export { LessonQuiz } from "./lesson/lesson-quiz/lesson-quiz.js";
export { LessonReveal } from "./lesson/lesson-reveal/lesson-reveal.js";
export { LessonRule } from "./lesson/lesson-rule/lesson-rule.js";
export { LessonStep } from "./lesson/lesson-step/lesson-step.js";
export { LessonSummary } from "./lesson/lesson-summary/lesson-summary.js";
export { LessonVocab } from "./lesson/lesson-vocab/lesson-vocab.js";
export { CeDocsLayout } from "./components/docs-layout/docs-layout.js";
export { CeNavList, type NavItem } from "./components/nav-list/nav-list.js";
export { CeThemeSwitcher, type ThemeSwitcherOption } from "./components/theme-switcher/theme-switcher.js";

// Core helpers (for consumers authoring their own components)
export { CecElement, defineOnce } from "./core/index.js";

// Manifest (machine-readable catalog + on-demand loader)
export {
  COMPONENTS,
  UI_COMPONENTS,
  LESSON_COMPONENTS,
  INTERNAL_COMPONENTS,
  loadOnDemand,
  type Category,
  type ComponentEntry,
} from "./manifest.js";

// Bulk registration
export { defineAll } from "./auto.js";
