// AUTO-GENERATED by scripts/generate-exports.ts — do not edit by hand.
// Source of truth: src/**/*.meta.json.


/**
 * Machine-readable catalog of every component shipped in this package.
 *
 * Consumers can use this for:
 *   - build-time discovery (which tags exist?)
 *   - docs generation
 *   - dynamic on-demand loading (see `loadOnDemand` below)
 */

export type Category = "ui" | "lesson" | "internal";

export interface ComponentEntry {
  /** Short subpath name (also the import specifier after the package name). */
  readonly name: string;
  /** Registered custom-element tag name. */
  readonly tag: string;
  /** Exported class name. */
  readonly className: string;
  /** Subpath import specifier (e.g. "custom-elements-collection/hero"). */
  readonly import: string;
  /** One-line human-readable description. */
  readonly description: string;
  readonly category: Category;
  /** Optional sub-group within the category (for sidebar sectioning). */
  readonly group?: string;
}

export const COMPONENTS: ReadonlyArray<ComponentEntry> = [
  { name: "bar-chart", tag: "ce-bar-chart", className: "CeBarChart", import: "custom-elements-collection/bar-chart", category: "ui", group: "Metrics & charts", description: "Data-driven horizontal bar chart. Takes a data array as a JS property or JSON attribute, auto-scales to the largest value when max is unset, and supports per-row color overrides. Each row exposes ARIA progressbar semantics for accessibility." },
  { name: "callout", tag: "ce-callout", className: "CeCallout", import: "custom-elements-collection/callout", category: "ui", group: "Layout & primitives", description: "Tinted left-border admonition box. Replaces drift between callout / admonition / alert / note / risk markup. Five semantic types color-code the border and background; an optional title overrides via attribute or named slot." },
  { name: "card", tag: "ce-card", className: "CeCard", import: "custom-elements-collection/card", category: "ui", group: "Layout & primitives", description: "Generic content card with title, body, and footer slots. Supports a colored left-border accent, hover-elevation, compact padding, and a clickable mode that adds role=button + Enter/Space activation and emits ce-card-activate." },
  { name: "chart", tag: "ce-chart", className: "CeChart", import: "custom-elements-collection/chart", category: "ui", group: "Metrics & charts", description: "Lazy-loaded Chart.js wrapper. On first update injects a <script src=…> for Chart.js if window.Chart is not already present, then mounts a chart on a managed canvas. Honors live updates to type / data / options by destroying and re-mounting. Renders an inline error block if the script fails to load." },
  { name: "chip", tag: "ce-chip", className: "CeChip", import: "custom-elements-collection/chip", category: "ui", group: "Layout & primitives", description: "Small inline status indicator. Replaces ad-hoc badge / pill / tag / label markup with one canonical element. Seven color types (neutral / green / red / amber / blue / purple / cyan), optional leading dot, and an outlined treatment for low-emphasis use." },
  { name: "code", tag: "ce-code", className: "CeCode", import: "custom-elements-collection/code", category: "ui", group: "Comparison & narrative", description: "Code block component. Header row shows an optional filename (left) and language label (right) plus a copy button when copy=true. Body is a <pre><code> with the slotted code text. The copy button uses navigator.clipboard with a hidden-textarea fallback and emits ce-code-copy on success." },
  { name: "compare", tag: "ce-compare", className: "CeCompare", import: "custom-elements-collection/compare", category: "ui", group: "Comparison & narrative", description: "Side-by-side comparison panel. Left column gets a red tint (Before), right column a green tint (After), and a center column shows a configurable arrow (default → ). Below 640px the layout collapses to a single column and the arrow hides." },
  { name: "decision-tree", tag: "ce-decision-tree", className: "CeDecisionTree", import: "custom-elements-collection/decision-tree", category: "ui", group: "Comparison & narrative", description: "Single-level decision tree component for if/then teaching diagrams. Renders a centered question and a responsive grid of branches; each branch declares yes / no / neutral kind, gets a tinted border + arrow label (↓ YES / ↓ NO / ↓), and shows label and result text." },
  { name: "details", tag: "ce-details", className: "CeDetails", import: "custom-elements-collection/details", category: "ui", group: "Layout & primitives", description: "Thin wrapper over native <details> with chevron rotation, hover state, an optional right-aligned count chip, and a custom toggle event. Reflects open to the host attribute so consumers can style or query collapsed state." },
  { name: "example", tag: "ce-example", className: "CeExample", import: "custom-elements-collection/example", category: "ui", group: "Comparison & narrative", description: "Color-coded example block. type=good tints green and labels 'Good'; type=bad tints red and labels 'Wrong'; type=neutral uses a neutral border and labels 'Example'. Consumers can override the label text via the label attribute." },
  { name: "feature-card", tag: "ce-feature-card", className: "CeFeatureCard", import: "custom-elements-collection/feature-card", category: "ui", group: "Comparison & narrative", description: "Marketing-style feature card. Top: tinted icon disk. Middle: title + slotted body. Bottom: optional CTA — rendered as an <a> when href is set, otherwise a <button> that emits ce-feature-cta. Six color tints adjust the icon disk." },
  { name: "filter-bar", tag: "ce-filter-bar", className: "CeFilterBar", import: "custom-elements-collection/filter-bar", category: "ui", group: "Comparison & narrative", description: "Chip-style filter bar. Each option becomes a pressable pill; aria-pressed reflects selection state. Single-select by default; multiple=true allows multi-select with the value attribute holding a comma-joined string." },
  { name: "flow", tag: "ce-flow", className: "CeFlow", import: "custom-elements-collection/flow", category: "ui", group: "Comparison & narrative", description: "Step-flow diagram. Boxes separated by arrows; each step can have a caption and a color tint. Vertical attribute stacks boxes top-to-bottom and switches the default arrow from → to ↓ (consumers can override with the arrow attribute)." },
  { name: "grid", tag: "ce-grid", className: "CeGrid", import: "custom-elements-collection/grid", category: "ui", group: "Layout & primitives", description: "Responsive grid container. Either uses a fixed column count (cols=2/3/4) or repeat(auto-fit, minmax(min, 1fr)) when auto is set. Below 640px the grid collapses to a single column." },
  { name: "heatmap", tag: "ce-heatmap", className: "CeHeatmap", import: "custom-elements-collection/heatmap", category: "ui", group: "Metrics & charts", description: "2D heatmap. Takes rows / cols / data arrays as JS properties or JSON attributes; colors each cell by interpolating the palette token between min and max (auto-detected when max is 0). Cell hover surfaces a focus outline." },
  { name: "hero", tag: "ce-hero", className: "CeHero", import: "custom-elements-collection/hero", category: "ui", group: "Layout & primitives", description: "Page header with eyebrow kicker, gradient-clipped title, lede paragraph, and a stats slot for inline KPIs. Provides a radial-gradient background by default; flat attribute suppresses it." },
  { name: "kpi", tag: "ce-kpi", className: "CeKpi", import: "custom-elements-collection/kpi", category: "ui", group: "Metrics & charts", description: "Single-stat KPI block — large value, small uppercase label, and optional inline trend (e.g. '+12%') that auto-colors based on its leading sign (+ green, - red, otherwise neutral). Used inside <ce-hero slot=\"stats\"> or in any grid row." },
  { name: "persona", tag: "ce-persona", className: "CePersona", import: "custom-elements-collection/persona", category: "ui", group: "Comparison & narrative", description: "Persona / role card. Top row shows an emoji-or-character avatar plus name + role; below sits a tags slot for chips and a default slot for an attribute list (typically a <dl>). Six color tints set the top border and avatar tint." },
  { name: "progress", tag: "ce-progress", className: "CeProgress", import: "custom-elements-collection/progress", category: "ui", group: "Metrics & charts", description: "Linear progress bar bound by value/max. Supports an optional left label, a numeric percent value on the right (show-value), an indeterminate shimmer, and five color tokens for the fill. Exposes ARIA progressbar semantics with valuemin / valuemax / valuenow / busy." },
  { name: "section", tag: "ce-section", className: "CeSection", import: "custom-elements-collection/section", category: "ui", group: "Layout & primitives", description: "Titled content section. Renders a header row containing an optional circular number badge, a heading, and an optional count chip on the right; underneath the row sits an optional lede paragraph and the default body slot. Used to break long pages into numbered chapters." },
  { name: "shell", tag: "ce-shell", className: "CeShell", import: "custom-elements-collection/shell", category: "ui", group: "Layout & primitives", description: "Page-level wrapper. Clamps content width (narrow / default / wide / full), applies the project's outer padding, and propagates the active theme to the document root via data-ce-theme so token CSS resolves correctly. Should be used at most once per page." },
  { name: "table", tag: "ce-table", className: "CeTable", import: "custom-elements-collection/table", category: "ui", group: "Layout & primitives", description: "Light-DOM-aware wrapper around a slotted <table>. Adds surface border, radius, horizontal scroll container, and ambient styles for headers, cells, hover, and special td classes (.num, .center, .mono). Sticky and compact attributes are honored via the ambient stylesheet." },
  { name: "timeline", tag: "ce-timeline", className: "CeTimeline", import: "custom-elements-collection/timeline", category: "ui", group: "Comparison & narrative", description: "Timeline of TimelineItem entries. Each item has a title, optional meta line (date/duration/owner), optional description, optional color for the dot, and optional icon character. Vertical (default) renders a connecting rail; horizontal renders a row of equally-sized columns." },
  { name: "toc", tag: "ce-toc", className: "CeToc", import: "custom-elements-collection/toc", category: "ui", group: "Layout & primitives", description: "Table of contents component. Accepts an entries array of { href, label } via property or JSON attribute; optionally numbers each entry and sticks to the top of its scroll parent. When entries is empty, falls back to the default slot so consumers can supply <a> children directly." },
  { name: "verdict", tag: "ce-verdict", className: "CeVerdict", import: "custom-elements-collection/verdict", category: "ui", group: "Comparison & narrative", description: "Decision banner with icon, title, and detail. Four semantic types tint the border, background, icon, and title color. Default icons are ✓ ✗ ⚠ ℹ; consumers can override via the icon attribute or supply custom title markup via the title slot." },
  { name: "lesson-audio", tag: "lesson-audio", className: "LessonAudio", import: "custom-elements-collection/lesson-audio", category: "lesson", group: "education", description: "Pronunciation / audio-clip button. Renders a play button (label is configurable, default '🔊 Play') plus an optional monospace phonetic string. First click instantiates a single HTMLAudioElement and plays it; subsequent plays reuse the same element. Error states show inline." },
  { name: "lesson-frame", tag: "lesson-frame", className: "LessonFrame", import: "custom-elements-collection/lesson-frame", category: "lesson", group: "education", description: "Top-level lesson shell. Renders a fixed 4px progress bar at the top of the viewport (driven by the progress prop), a centered title + meta row, and a content column with a max-width of 880px. Used as the outermost element on a lesson page." },
  { name: "lesson-gap", tag: "lesson-gap", className: "LessonGap", import: "custom-elements-collection/lesson-gap", category: "lesson", group: "education", description: "Fill-in-the-blank exercise. Splits the prompt at the first '___' marker and renders the gap as a colored span; below sit the options as buttons. After the user picks, the chosen button colors green or red, the gap fills with the correct answer when correct, and a feedback strip shows the explanation. lesson-gap-answer fires once per exercise." },
  { name: "lesson-quickfire", tag: "lesson-quickfire", className: "LessonQuickfire", import: "custom-elements-collection/lesson-quickfire", category: "lesson", group: "education", description: "Timed practice round. Cycles through QuickfireRound entries; each round shows the prompt, options, and a thin timer bar that empties over `timer` seconds. Pick: correct flashes green and increments score; wrong flashes red. After the last round emits lesson-quickfire-done; reset() restarts." },
  { name: "lesson-quiz", tag: "lesson-quiz", className: "LessonQuiz", import: "custom-elements-collection/lesson-quiz", category: "lesson", group: "education", description: "Single-question multiple-choice quiz. Renders a question and a vertical list of options; clicking an option marks it green if correct or red if wrong (and outlines the correct one), shows the explanation below, and disables the rest. lesson-quiz-answer fires once per question." },
  { name: "lesson-rule", tag: "lesson-rule", className: "LessonRule", import: "custom-elements-collection/lesson-rule", category: "lesson", group: "education", description: "Rule card for educational content. Top row shows a circular blue badge (number / glyph / ★) plus a title; below sits a slotted body. golden=true switches to amber styling for emphasized, top-of-lesson rules." },
];

/**
 * Dynamic on-demand loader — resolves a subset of components by tag or name
 * via native ESM `import()`. Bundlers tree-shake the unused branches.
 *
 *   await loadOnDemand(["ce-hero", "ce-kpi"]);
 *   await loadOnDemand("lesson-rule");
 */
export async function loadOnDemand(
  selection: string | ReadonlyArray<string>
): Promise<void> {
  const wanted = typeof selection === "string" ? [selection] : selection;
  const set = new Set(wanted);
  const matched = COMPONENTS.filter(
    (c) => set.has(c.tag) || set.has(c.name)
  );
  await Promise.all(matched.map((c) => import(/* @vite-ignore */ c.import)));
}

/** Filter helper: all UI components. */
export const UI_COMPONENTS = COMPONENTS.filter((c) => c.category === "ui");

/** Filter helper: all lesson components. */
export const LESSON_COMPONENTS = COMPONENTS.filter((c) => c.category === "lesson");

/** Filter helper: all internal / layout components. */
export const INTERNAL_COMPONENTS = COMPONENTS.filter((c) => c.category === "internal");
